services:
  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://book_shop_db_compose/postgres"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=postgres"
  postgres:
    image: postgres
    container_name: book_shop_db_compose
    environment:
      - "POSTGRES_PASSWORD=postgres"
